---

- name: first play
  hosts: all
  tasks:
    - name: create a new file
      file:
        path: /tmp/foo.conf
        mode: 0664
        owner: ubuntu
        state: touch

- name: create groups
  tasks:
    import_tasks:
      file: group-tasks.yml
