---

#A playbook archive.yml that runs on hosts in the database test group and
#does the following:
#• A directory /backup is created.
#• A gzip archive of all the files in /var/log is created and stored in /backup/logs.tar.gz


- name: To create a directory and store archived files
  hosts: test
  tasks:
    - name: To create directory
      file:
        path: /backup
        state: directory

    - name: To archive files
      archive:
        path: /var/log
        dest: /backup/log.tar.gz
        format: gz
